CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS cards (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    damage INTEGER DEFAULT 0,
    health INTEGER DEFAULT 2,
    armor INTEGER DEFAULT 0

);
CREATE TABLE IF NOT EXISTS users_cards (
    user_id INTEGER NOT NULL,
    card_id INTEGER NOT NULL,
    current_level INTEGER DEFAULT 0,
    current_exp INTEGER DEFAULT 0,

    PRIMARY KEY (user_id, card_id),

    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (card_id) REFERENCES cards(id)
);